// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelProcessing() {
  return window['go']['main']['App']['CancelProcessing']();
}

export function GeneratePreview(arg1) {
  return window['go']['main']['App']['GeneratePreview'](arg1);
}

export function GetDefaultOutputFolder() {
  return window['go']['main']['App']['GetDefaultOutputFolder']();
}

export function GetTemplateBackground(arg1) {
  return window['go']['main']['App']['GetTemplateBackground'](arg1);
}

export function LoadTemplate(arg1) {
  return window['go']['main']['App']['LoadTemplate'](arg1);
}

export function ProcessBatch(arg1) {
  return window['go']['main']['App']['ProcessBatch'](arg1);
}

export function SelectFrameFile() {
  return window['go']['main']['App']['SelectFrameFile']();
}

export function SelectOutputFolder() {
  return window['go']['main']['App']['SelectOutputFolder']();
}

export function SelectProductFiles() {
  return window['go']['main']['App']['SelectProductFiles']();
}

export function SelectTemplateFile() {
  return window['go']['main']['App']['SelectTemplateFile']();
}
