// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {models} from '../models';

export function CancelProcessing():Promise<void>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function GeneratePreview(arg1:models.ProcessRequest):Promise<string>;

export function GetDefaultOutputFolder():Promise<string>;

export function GetTemplateBackground(arg1:string):Promise<string>;

export function GetVersion():Promise<string>;

export function LoadTemplate(arg1:string):Promise<Array<string>>;

export function ProcessBatch(arg1:models.ProcessRequest):Promise<void>;

export function SelectFrameFile():Promise<string>;

export function SelectOutputFolder():Promise<string>;

export function SelectProductFiles():Promise<Array<string>>;

export function SelectTemplateFile():Promise<string>;
